"use client";
import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const DICTIONARY = {
  en: {
    dir: "ltr",
    lang: "en",
    brandNamePart1: "MERKATO",
    brandNamePart2: "STORE",
    subtitle: "Pan-African & Middle East Marketplace",
    searchPlaceholder: "Search 5,000+ regional products...",
    btnCart: "Add to Cart",
    basketTitle: "Basket Summary",
    basketEmpty: "Basket is empty.",
    totalEst: "Estimated Total",
    checkoutBtn: "Proceed to Checkout",

    allProducts: "ALL PRODUCTS",
    electronics: "ELECTRONICS",
    fashion: "FASHION & CLOTHING",
    groceries: "GROCERIES",
    beauty: "BEAUTY PRODUCTS",
    household: "HOUSEHOLD ITEMS",
    accessories: "ACCESSORIES",

    deliverTo: "DELIVER TO",
    dashboard: "Dashboard",
    adminBadge: "ADMIN",
    logout: "Logout",
    signIn: "SIGN IN",
    signUp: "SIGN UP",
    forgotPassword: "Forgot Password?",

    footerCopy:
      "© 2026 Merkato Store Marketplace Hub. All multi-region routes secured via PCI-DSS Level 1 specifications.",
    footerSecurity: "TLS 1.3 Secure Deployment Pipeline",
    marketplaceSubtitle: "Pan-African & Middle East Marketplace",
    total: "Total:",
    footerShop: "Shop",
    footerAccount: "Account",
    footerSupport: "Support",
    myAccount: "My Account",
    footerCheckout: "Checkout",
    trackOrder: "Track an Order",
    securePayments: "Secure Payments",
    deliveryFreight: "Delivery & Freight",
    footerCopyright: "© {year} Merkato Store Marketplace — All multi-region routes secured.",
    stripeSecure: "Stripe Secure",
    regionalHubs: "6 Regional Hubs",
    footerTagline:
      "Pan-African & Middle East marketplace — curated goods, secure freight, and regional commerce in one place.",
    marketplaceTitle: "Marketplace",
    resultsFor: "Results for {term}",
    itemsCount: "{n} items",
    trustFreight: "Fast Freight",
    trustFreightSub: "Cross-border delivery",
    trustSecure: "Secure Payments",
    trustSecureSub: "Stripe encrypted",
    trustCurrency: "Local Currency",
    trustCurrencySub: "6 regional markets",
    trustSupport: "24/7 Support",
    trustSupportSub: "Always available",
    noProductsFound: "No items were found under category {term}.",
    loadingStore: "Loading store...",
    addToCartShort: "Add",
    featuredTitle: "Featured Products",
    viewAll: "View all",
    specialOffers: "Special Offers",
    sale: "Sale",
    startBrowsing: "Start browsing",
    soldOut: "Sold Out",
    inStock: "In Stock",
    genericBrand: "Generic",
    fewLeft: "Only a few left",
    skuLabel: "SKU:",
    brandSplit: "Brand:",
    buyerReviews: "Buyer Reviews ({n})",
    noReviews:
      "No reviews yet for this product. Be the first to review it from your account dashboard.",
    verifiedBuyer: "Verified Buyer",
    categoriesFilter: "Categories Filter",
    categoryAll: "All",
    noItemsFound: "No items found for the selected category or search.",
    loadingProducts: "Loading products...",
    loadingRecentOrders: "Loading recent orders...",
    cartTitle: "Your Cart",
    cartSubtitle: "Review your items, adjust quantities, or remove them.",
    cartEmpty: "Your cart is empty.",
    returnToStore: "Return to Store",
    subtotal: "Subtotal:",
    freightNote: "Freight & regional tax are added at checkout.",
    secureCheckout: "Secure Checkout",
    checkoutSubtitle: "Enter your shipping details and pay securely with Stripe.",
    yourOrder: "Your Order",
    shippingDetails: "Shipping Details",
    fullName: "Full Name *",
    phone: "Phone Number *",
    street: "Street Address *",
    city: "City *",
    promoCode: "Promo Code",
    promoPlaceholder: "E.G. MERKATO20",
    apply: "Apply",
    promoApplied: "✓ Code applied! Deducting {n}% off your items.",
    promoInvalid: "That promo code is not valid.",
    orderSummary: "Order Summary",
    itemsSubtotal: "Items subtotal:",
    discountLabel: "Discount:",
    shippingLabel: "Shipping:",
    taxLabel: "Tax ({n}%):",
    payNow: "Pay Now",
    processingPayment: "Processing payment...",
    fillShipping: "Please fill all shipping fields.",
    paymentFailed: "Payment failed. Please try again.",
    paymentSuccess: "Payment Successful",
    paymentSuccessBody:
      "Your order has been placed and payment confirmed via Stripe. Check your account for tracking details.",
    viewMyOrders: "View My Orders",
    continueShopping: "Continue Shopping",
    marketLabel: "Market:",
    inTransitStat: "In Transit:",
    wishlistStat: "Wishlist:",
    tabOrders: "My Orders",
    tabProfile: "Profile & Addresses",
    tabWishlist: "Saved Wishlist",
    tabReviews: "Reviews",
    noOrdersYet: "No orders yet — your shipment log is empty.",
    startShopping: "Start shopping →",
    trackingRef: "Tracking Ref:",
    dateLabel: "Date:",
    totalPaid: "Total Paid:",
    deliveryUpdates: "📡 Delivery Updates:",
    trackingNumber: "Tracking number:",
    destination: "Destination:",
    myAddresses: "My Addresses",
    remove: "Remove",
    addAddressPlaceholder: "Add a new address...",
    failedSaveAddress: "Failed to save address.",
    myWishlist: "My Wishlist",
    wishlistEmpty:
      "No saved items yet. Tap the heart icon on any product to save it here.",
    submitReview: "Submit a Review",
    productLabel: "Product",
    searchProductPlaceholder: "Search product to review...",
    noMatch: "No products match",
    selectedLabel: "Selected:",
    yourRating: "Your Rating",
    ratingExcellent: "★★★★★ Excellent",
    ratingGood: "★★★★☆ Good",
    ratingAverage: "★★★☆☆ Average",
    yourReview: "Your Review",
    writeReviewPlaceholder: "Write your review here...",
    submitReviewCta: "Submit Review",
    reviewSubmitted: "✓ Review submitted! Added {n}-star rating.",
    reviewSelectProduct: "Select a product to review first.",
    reviewFailed: "Failed to submit review.",
    welcomeBackBig: "Welcome back",
    welcomeBackSuffix: "to the marketplace.",
    loginBody:
      "Sign in to resume shopping across six regional hubs with secure freight, customs clearance, and parcel telemetry delivered to your doorstep.",
    secureCheckoutTag: "Secure checkout",
    encryptedTelemetry: "Encrypted telemetry",
    logistics24h: "24h logistics",
    welcomeBack: "Welcome Back",
    loginSubtitle: "Sign in to continue to your marketplace account.",
    emailAddress: "Email Address",
    password: "Password",
    emailPlaceholder: "you@example.com",
    passwordPlaceholder: "Enter your password",
    signInBtn: "Sign In",
    loggingIn: "Logging in...",
    forgotLink: "Forgot your password?",
    noAccount: "Don't have an account?",
    createOne: "Create one",
    joinThe: "Join the",
    joinSuffix: "marketplace.",
    signupBody:
      "Create your account to shop across six regional hubs with secure freight, customs clearance, and parcel telemetry delivered to your doorstep.",
    freeToJoin: "Free to join",
    sixHubs: "Six regional hubs",
    fillDetails: "Fill in your details to get started.",
    johnDoe: "John Doe",
    country: "Country",
    minPassword: "Minimum 6 characters",
    confirmPassword: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm your password",
    adminOptional: "Admin Code (optional)",
    adminPlaceholder: "Leave empty for regular account",
    creatingAccount: "Creating account...",
    haveAccount: "Already have an account?",
    logIn: "Log In",
    accountCreated: "Account Created",
    accountCreatedBody: "Your account has been created successfully. You can now log in.",
    goToLogin: "Go to Login",
    passwordsMismatch: "Passwords do not match.",
    registrationFailed: "Registration failed.",
    resetPassword: "Reset Password",
    resetSubtitle: "Provide your account email to receive a recovery access token payload.",
    accountEmail: "Account Email Address",
    emailExample: "e.g. abebe@merkatostore.com",
    requestResetLink: "Request Reset Link",
    sendingResetLink: "Sending reset link...",
    recoverySent:
      "🎉 Recovery email sent! Check your inbox for instructions to reset your password.",
    returnToLogin: "Return to Login",
    tryAgain: "Something went wrong. Please try again.",
    loggingOutTitle: "Securing Your Session Teardown",
    loggingOutBody:
      "Wiping localized security configuration matrices and routing your connection safely back onto the store timeline...",
    adminDashboard: "Admin Dashboard",
    adminOverview: "Store overview: orders, revenue, and products.",
    backToStore: "← Back to Store",
    last24h: "Last 24 Hours",
    last7d: "Last 7 Days",
    last30d: "Last 30 Days",
    totalRevenue: "Total Revenue",
    paidOrders: "Paid Orders",
    activeOrders: "Active Orders",
    totalShort: "Total",
    lowStock: "Low Stock",
    items: "Items",
    needsReplenishment: "Needs Replenishment",
    productsTitle: "Products",
    inCatalog: "In catalog",
    statusDistribution: "Order Status Distribution",
    noOrders: "No orders yet.",
    quickActions: "Quick Actions:",
    manageProducts: "📁 Manage Products",
    manageOrders: "Manage Orders",
    recentOrders: "Recent Orders",
    recentOrdersSub: "Latest orders and their status.",
    destinationPending: "Destination pending",
    ordersTitle: "Orders",
    ordersSub: "Approve and update orders as they move through shipping and delivery.",
    backToDashboard: "← Back to Dashboard",
    hOrderId: "Order ID",
    hCustomer: "Customer & Destination",
    hItems: "Items",
    hTotal: "Total Paid",
    hStatus: "Status",
    hActions: "Actions",
    customerAccount: "Customer Account",
    awaitingDetails: "Awaiting details",
    approveShip: "Approve & Ship",
    markDelivered: "Mark Delivered",
    cancel: "Cancel",
    completed: "Completed",
    stAwaitingPayment: "Awaiting Payment",
    stPaidProcessing: "Paid — Processing",
    stInTransit: "In Transit",
    stDelivered: "Delivered",
    stCancelled: "Cancelled / Refunded",
    failedUpdateStatus: "Failed to update order status.",
    manageProductsTitle: "Manage Products",
    manageProductsSub: "Add, edit, or delete products in your catalog.",
    editProduct: "✏️ Edit Product",
    addProduct: "➕ Add Product",
    lblProductName: "Product Name",
    lblSku: "SKU",
    lblBrand: "Brand",
    lblCategory: "Category",
    lblPrice: "Price ($)",
    lblStock: "Stock",
    saveProduct: "Save Product",
    addProductCta: "Add Product",
    productCatalog: "Product Catalog",
    thProduct: "Product",
    thCategory: "Category",
    thPrice: "Price",
    thStock: "Stock",
    thActions: "Actions",
    edit: "Edit",
    delete: "Delete",
    noProductsInCatalog: "No products in the catalog yet.",
    units: "units",
    fillRequiredFields: "Please fill all required fields.",
    failedSaveProduct: "Failed to save product.",
    confirmDeleteProduct: "Delete this product?",
    failedDeleteProduct: "Failed to delete product.",
    phProductName: "e.g. AcousticMax Wireless Pro",
    phBrand: "e.g. AlphaSonic Labs",
  },
  ar: {
    dir: "rtl",
    lang: "ar",
    brandNamePart1: "ميركاتو",
    brandNamePart2: "متجر",
    subtitle: "التجارة الإلكترونية عبر أفريقيا والشرق الأوسط",
    searchPlaceholder: "ابحث في أكثر من ٥,٠٠٠ منتج...",
    btnCart: "أضف إلى السلة",
    basketTitle: "ملخص سلة التسوق",
    basketEmpty: "السلة فارغة.",
    totalEst: "الإجمالي التقديري",
    checkoutBtn: "المتابعة لإتمام الشراء",

    allProducts: "جميع المنتجات",
    electronics: "الإلكترونيات",
    fashion: "الأزياء والملابس",
    groceries: "البقالة",
    beauty: "منتجات التجميل",
    household: "المستلزمات المنزلية",
    accessories: "الإكسسوارات",

    deliverTo: "يتم الشحن إلى",
    dashboard: "لوحة التحكم",
    adminBadge: "مسؤول",
    logout: "تسجيل الخروج",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    forgotPassword: "هل نسيت كلمة المرور؟",

    footerCopy:
      "© ٢٠٢٦ مركز سوق متجر ميركاتو. جميع المسارات متعددة المناطق مؤمنة وفقًا لمواصفات PCI-DSS من المستوى ١.",
    footerSecurity: "قناة النشر الآمنة TLS 1.3",
  },
  am: {
    dir: "ltr",
    lang: "am",
    brandNamePart1: "መርካቶ",
    brandNamePart2: "ሱቅ",
    subtitle: "የአፍሪካ እና የመካከለኛው ምስራቅ የገበያ አዳራሽ",
    searchPlaceholder: "ከ5,000 በላይ እቃዎችን እዚህ ይፈልጉ...",
    btnCart: "ወደ ቅርጫት ጨምር",
    basketTitle: "የቅርጫት ማጠቃለያ",
    basketEmpty: "ቅርጫትዎ ባዶ ነው።",
    totalEst: "አጠቃላይ ድምር ዋጋ",
    checkoutBtn: "ወደ ክፍያ ሂድ",

    allProducts: "ሁሉንም ምርቶች",
    electronics: "ኤሌክትሮኒክስ",
    fashion: "አልባሳትና ፋሽን",
    groceries: "ግሮሰሪና ሸቀጣሸቀጥ",
    beauty: "የውበት መጠበቂያዎች",
    household: "የቤት ውስጥ ቁሶች",
    accessories: "አክሰሰሪዎች",

    deliverTo: "የሚላከው ወደ",
    dashboard: "ዳሽቦርድ",
    adminBadge: "አስተዳዳሪ",
    logout: "ውጣ",
    signIn: "ግባ",
    signUp: "ተመዝገብ",
    forgotPassword: "የይለፍ ቃል ረስተዋል?",

    footerCopy:
      "© 2026 መርካቶ ስቶር የገበያ ማዕከል። ሁሉም ክልላዊ የጉዞ መስመሮች በPCI-DSS ደረጃ 1 መግለጫዎች የተጠበቁ ናቸው。",
    footerSecurity: "TLS 1.3 ደህንነቱ የተጠበቀ የዝርጋታ መስመር",
    marketplaceSubtitle: "የፓን-አፍሪካ እና የመካከለኛው ምስራቅ የገበያ ስፍራ",
    total: "ድምር:",
    footerShop: "ገበያ",
    footerAccount: "አካውንት",
    footerSupport: "ድጋፍ",
    myAccount: "የኔ አካውንት",
    footerCheckout: "ክፍያ",
    trackOrder: "ትዕዛዝዎን ይከታተሉ",
    securePayments: "ደህንነቱ የተጠበቀ ክፍያ",
    deliveryFreight: "ማድረሻ እና ጭነት",
    footerCopyright: "© {year} Merkato Store Marketplace — ሁሉም የባለብዙ-ቀጠና መስመሮች ደህንነታቸው የተጠበቀ ነው።",
    stripeSecure: "Stripe Secure",
    regionalHubs: "6 የቀጠና ማዕከላት",
    footerTagline: "የፓን-አፍሪካ እና የመካከለኛው ምስራቅ የገበያ ስፍራ — የተመረጡ ዕቃዎች፣ ደህንነቱ የተጠበቀ ጭነት እና የቀጠና ንግድ በአንድ ቦታ።",
    marketplaceTitle: "የገበያ ስፍራ",
    resultsFor: "ለ {term} የተገኙ ውጤቶች",
    itemsCount: "{n} ዕቃዎች",
    trustFreight: "ፈጣን ጭነት",
    trustFreightSub: "ድንበር ተሻጋሪ ማድረሻ",
    trustSecure: "ደህንነቱ የተጠበቀ ክፍያ",
    trustSecureSub: "Stripe የተመሰጠረ",
    trustCurrency: "የሀገር ውስጥ ምንዛሬ",
    trustCurrencySub: "6 የቀጠና ገበያዎች",
    trustSupport: "የ24/7 ድጋፍ",
    trustSupportSub: "ሁልጊዜም ዝግጁ",
    noProductsFound: "በ {term} ምድብ ስር ምንም ዕቃዎች አልተገኙም።",
    loadingStore: "ሱቁን በመክፈት ላይ...",
    addToCartShort: "ጨምር",
    featuredTitle: "ምርጥ ምርቶች",
    viewAll: "ሁሉንም ይመልከቱ",
    specialOffers: "ልዩ ቅናሾች",
    sale: "ቅናሽ",
    startBrowsing: "መገዛት ይጀምሩ",
    soldOut: "አልቋል",
    inStock: "በክምችት አለ",
    genericBrand: "ጀነሪክ",
    fewLeft: "ጥቂት ብቻ ቀርተዋል",
    skuLabel: "SKU:",
    brandSplit: "ብራንድ:",
    buyerReviews: "የገዢ ግምገማዎች ({n})",
    noReviews: "ለዚህ ምርት እስካሁን ምንም ግምገማዎች የሉም። ከአካውንትዎ ዳሽቦርድ የመጀመሪያው ገምጋሚ ይሁኑ።",
    verifiedBuyer: "የተረጋገጠ ገዢ",
    categoriesFilter: "የምድቦች ማጣሪያ",
    categoryAll: "ሁሉም",
    noItemsFound: "ለተመረጠው ምድብ ወይም ፍለጋ ምንም ዕቃዎች አልተገኙም።",
    loadingProducts: "ምርቶችን በማምጣት ላይ...",
    loadingRecentOrders: "የቅርብ ጊዜ ትዕዛዞችን በማምጣት ላይ...",
    cartTitle: "የርስዎ ዘንቢል",
    cartSubtitle: "ዕቃዎችዎን ይገምግሙ፣ መጠናቸውን ያስተካክሉ ወይም ያስወግዷቸው።",
    cartEmpty: "ዘንቢልዎ ባዶ ነው።",
    returnToStore: "ወደ ሱቅ ይመለሱ",
    subtotal: "ንዑስ ድምር:",
    freightNote: "የጭነት እና የቀጠና ታክስ በክፍያ ጊዜ ይታከላሉ።",
    secureCheckout: "ደህንነቱ የተጠበቀ ክፍያ",
    checkoutSubtitle: "የማድረሻ ዝርዝርዎን ያስገቡ እና በ Stripe ደህንነቱ በተጠበቀ ሁኔታ ይክፈሉ።",
    yourOrder: "የርስዎ ትዕዛዝ",
    shippingDetails: "የማድረሻ ዝርዝሮች",
    fullName: "ሙሉ ስም *",
    phone: "ስልክ ቁጥር *",
    street: "የመንገድ አድራሻ *",
    city: "ከተማ *",
    promoCode: "የቅናሽ ኮድ",
    promoPlaceholder: "E.G. MERKATO20",
    apply: "ተግብር",
    promoApplied: "✓ ኮዱ ተተግብሯል! ከዕቃዎችዎ ላይ {n}% ቀንሰናል።",
    promoInvalid: "የቅናሽ ኮዱ ትክክል አይደለም።",
    orderSummary: "የትዕዛዝ ማጠቃለያ",
    itemsSubtotal: "የዕቃዎች ንዑስ ድምር:",
    discountLabel: "ቅናሽ:",
    shippingLabel: "ማድረሻ:",
    taxLabel: "ታክስ ({n}%):",
    payNow: "አሁን ይክፈሉ",
    processingPayment: "ክፍያውን በማስኬድ ላይ...",
    fillShipping: "እባክዎ ሁሉንም የማድረሻ ቦታዎች ይሙሉ::",
    paymentFailed: "ክፍያው አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
    paymentSuccess: "ክፍያው ተሳክቷል",
    paymentSuccessBody: "ትዕዛዝዎ ገብቷል ክፍያዎም በ Stripe ተረጋግጧል። ለመከታተያ ዝርዝሮች አካውንትዎን ያረጋግጡ።",
    viewMyOrders: "ትዕዛዞቼን ይመልከቱ",
    continueShopping: "ግብይት ይቀጥሉ",
    marketLabel: "ገበያ:",
    inTransitStat: "በመጓጓዝ ላይ:",
    wishlistStat: "ምኞት ዝርዝር:",
    tabOrders: "የኔ ትዕዛዞች",
    tabProfile: "ፕሮፋይል እና አድራሻዎች",
    tabWishlist: "የተቀመጡ ምኞት ዝርዝር",
    tabReviews: "ግምገማዎች",
    noOrdersYet: "እስካሁን ምንም ትዕዛዞች የሉም — የጭነት መዝገብዎ ባዶ ነው።",
    startShopping: "ግብይት ይጀምሩ →",
    trackingRef: "መከታተያ ቁጥር:",
    dateLabel: "ቀን:",
    totalPaid: "የተከፈለ ድምር:",
    deliveryUpdates: "📡 የማድረሻ ዝመናዎች:",
    trackingNumber: "መከታተያ ቁጥር:",
    destination: "መዳረሻ:",
    myAddresses: "የኔ አድራሻዎች",
    remove: "አስወግድ",
    addAddressPlaceholder: "አዲስ አድራሻ ያክሉ...",
    failedSaveAddress: "አድራሻውን ማስቀመጥ አልተሳካም።",
    myWishlist: "የኔ ምኞት ዝርዝር",
    wishlistEmpty: "እስካሁን ምንም የተቀመጡ ዕቃዎች የሉም። እዚህ ለማስቀመጥ በማንኛውም ምርት ላይ ያለውን የልብ ምልክት ይንኩ።",
    submitReview: "ግምገማ ያስገቡ",
    productLabel: "ምርት",
    searchProductPlaceholder: "ለመገምገም ምርት ይፈልጉ...",
    noMatch: "የሚዛመዱ ምርቶች የሉም",
    selectedLabel: "የተመረጠ:",
    yourRating: "ደረጃዎ",
    ratingExcellent: "★★★★★ በጣም ጥሩ",
    ratingGood: "★★★★☆ ጥሩ",
    ratingAverage: "★★★☆☆ አማካይ",
    yourReview: "ግምገማዎ",
    writeReviewPlaceholder: "ግምገማዎን እዚህ ይፃፉ...",
    submitReviewCta: "ግምገማ ያስገቡ",
    reviewSubmitted: "✓ ግምገማው ገብቷል! ባለ {n}-ኮከብ ደረጃ ታክሏል።",
    reviewSelectProduct: "በመጀመሪያ ለመገምገም ምርት ይምረጡ።",
    reviewFailed: "ግምገማውን ማስገባት አልተሳካም።",
    welcomeBackBig: "እንኳን ደህና ተመለሱ",
    welcomeBackSuffix: "ወደ የገበያ ስፍራው።",
    loginBody: "በስድስት የቀጠና ማዕከላት ደህንነቱ በተጠበቀ ጭነት፣ የጉምሩክ ማጣራት እና የእሽግ ክትትል እስከ ደጃፍዎ ለማድረስ ግብይት ለመቀጠል ይግቡ።",
    secureCheckoutTag: "ደህንነቱ የተጠበቀ ክፍያ",
    encryptedTelemetry: "የተመሰጠረ ክትትል",
    logistics24h: "የ24 ሰዓት ሎጂስቲክስ",
    welcomeBack: "እንኳን ደህና ተመለሱ",
    loginSubtitle: "ወደ እርስዎ የገበያ ስፍራ አካውንት ለመቀጠል ይግቡ።",
    emailAddress: "የኢሜይል አድራሻ",
    password: "የይለፍ ቃል",
    emailPlaceholder: "you@example.com",
    passwordPlaceholder: "የይለፍ ቃልዎን ያስገቡ",
    signInBtn: "ይግቡ",
    loggingIn: "በመግባት ላይ...",
    forgotLink: "የይለፍ ቃል ረሱ?",
    noAccount: "አካውንት የለዎትም?",
    createOne: "አዲስ ይፍጠሩ",
    joinThe: "ይቀላቀሉ",
    joinSuffix: "የገበያ ስፍራውን።",
    signupBody: "በስድስት የቀጠና ማዕከላት ደህንነቱ በተጠበቀ ጭነት፣ የጉምሩክ ማጣራት እና የእሽግ ክትትል እስከ ደጃፍዎ ለማድረስ አካውንትዎን ይፍጠሩ።",
    freeToJoin: "ለመቀላቀል ነፃ",
    sixHubs: "ስድስት የቀጠና ማዕከላት",
    fillDetails: "ለመጀመር ዝርዝሮችዎን ይሙሉ::",
    fullName: "ሙሉ ስም",
    johnDoe: "John Doe",
    country: "ሀገር",
    minPassword: "ቢያንስ 6 ቁምፊዎች",
    confirmPassword: "የይለፍ ቃል ያረጋግጡ",
    confirmPasswordPlaceholder: "የይለፍ ቃልዎን ያረጋግጡ",
    adminOptional: "የአድሚን ኮድ (አማራጭ)",
    adminPlaceholder: "ለመደበኛ አካውንት ባዶ ይተዉት",
    creatingAccount: "አካውንት በመፍጠር ላይ...",
    haveAccount: "አስቀድመው አካውንት አሎት?",
    logIn: "ይግቡ",
    accountCreated: "አካውንት ተፈጥሯል",
    accountCreatedBody: "አካውንትዎ በተሳካ ሁኔታ ተፈጥሯል። አሁን መግባት ይችላሉ።",
    goToLogin: "ወደ መግቢያ ይሂዱ",
    passwordsMismatch: "የይለፍ ቃሎቹ አይዛመዱም።",
    registrationFailed: "ምዝገባው አልተሳካም።",
    resetPassword: "የይለፍ ቃል ይቀይሩ",
    resetSubtitle: "የመልሶ ማግኛ ቶከን ለመቀበል የአካውንት ኢሜይልዎን ያቅርቡ።",
    accountEmail: "የአካውንት ኢሜይል አድራሻ",
    emailExample: "e.g. abebe@merkatostore.com",
    requestResetLink: "የመቀየሪያ ሊንክ ይጠይቁ",
    sendingResetLink: "የመቀየሪያ ሊንክ በመላክ ላይ...",
    recoverySent: "🎉 የመልሶ ማግኛ ኢሜይል ተልኳል! የይለፍ ቃልዎን ለመቀየር መመሪያዎችን ለማግኘት የገቢ መልዕክት ሳጥንዎን ያረጋግጡ።",
    returnToLogin: "ወደ መግቢያ ይመለሱ",
    tryAgain: "የሆነ ችግር ተከስቷል። እባክዎ እንደገና ይሞክሩ።",
    loggingOutTitle: "ሴሽንዎን በደህንነት በማቋረጥ ላይ",
    loggingOutBody: "አካባቢያዊ የደህንነት ውቅረቶችን በማፅዳት እና ግንኙነትዎን ወደ ሱቁ ደህንነቱ በተጠበቀ ሁኔታ በመመለስ ላይ...",
    adminDashboard: "የአድሚን ዳሽቦርድ",
    adminOverview: "የሱቅ አጠቃላይ ዕይታ: ትዕዛዞች፣ ገቢ እና ምርቶች።",
    backToStore: "← ወደ ሱቅ ይመለሱ",
    last24h: "ባለፉት 24 ሰዓታት",
    last7d: "ባለፉት 7 ቀናት",
    last30d: "ባለፉት 30 ቀናት",
    totalRevenue: "አጠቃላይ ገቢ",
    paidOrders: "የተከፈሉ ትዕዛዞች",
    activeOrders: "ንቁ ትዕዛዞች",
    totalShort: "ድምር",
    lowStock: "አነስተኛ ክምችት",
    items: "ዕቃዎች",
    needsReplenishment: "መሞላት ያለበት",
    productsTitle: "ምርቶች",
    inCatalog: "በካታሎግ ውስጥ",
    statusDistribution: "የትዕዛዝ ሁኔታ ስርጭት",
    noOrders: "እስካሁን ምንም ትዕዛዞች የሉም።",
    quickActions: "ፈጣን እርምጃዎች:",
    manageProducts: "📁 ምርቶችን ያስተዳድሩ",
    manageOrders: "ትዕዛዞችን ያስተዳድሩ",
    recentOrders: "የቅርብ ጊዜ ትዕዛዞች",
    recentOrdersSub: "የቅርብ ጊዜ ትዕዛዞች እና ሁኔታቸው።",
    destinationPending: "መዳረሻ በመጠባበቅ ላይ",
    ordersTitle: "ትዕዛዞች",
    ordersSub: "በማጓጓዣ እና ማድረሻ ሂደት ውስጥ የሚያልፉ ትዕዛዞችን ያፅድቁ እና ያዘምኑ።",
    backToDashboard: "← ወደ ዳሽቦርድ ይመለሱ",
    hOrderId: "የትዕዛዝ መታወቂያ",
    hCustomer: "ደንበኛ እና መዳረሻ",
    hItems: "ዕቃዎች",
    hTotal: "የተከፈለ ድምር",
    hStatus: "ሁኔታ",
    hActions: "እርምጃዎች",
    customerAccount: "የደንበኛ አካውንት",
    awaitingDetails: "ዝርዝሮችን በመጠባበቅ ላይ",
    approveShip: "አፅድቅ እና ላክ",
    markDelivered: "እንደደረሰ አድርግ",
    cancel: "ሰርዝ",
    completed: "ተጠናቋል",
    stAwaitingPayment: "ክፍያ በመጠባበቅ ላይ",
    stPaidProcessing: "ተከፍሏል — በሂደት ላይ",
    stInTransit: "በመጓጓዝ ላይ",
    stDelivered: "ደርሷል",
    stCancelled: "ተሰርዟል / ተመላሽ ተደርጓል",
    failedUpdateStatus: "የትዕዛዝ ሁኔታን ማዘመን አልተሳካም።",
    manageProductsTitle: "ምርቶችን ያስተዳድሩ",
    manageProductsSub: "በካታሎግዎ ውስጥ ምርቶችን ያክሉ፣ ያርትዑ ወይም ይሰርዙ።",
    editProduct: "✏️ ምርት ያርትዑ",
    addProduct: "➕ ምርት ያክሉ",
    lblProductName: "የምርት ስም",
    lblSku: "SKU",
    lblBrand: "ብራንድ",
    lblCategory: "ምድብ",
    lblPrice: "ዋጋ ($)",
    lblStock: "ክምችት",
    saveProduct: "ምርት አስቀምጥ",
    addProductCta: "ምርት ያክሉ",
    productCatalog: "የምርት ካታሎግ",
    thProduct: "ምርት",
    thCategory: "ምድብ",
    thPrice: "ዋጋ",
    thStock: "ክምችት",
    thActions: "እርምጃዎች",
    edit: "አርትዕ",
    delete: "ሰርዝ",
    noProductsInCatalog: "እስካሁን በካታሎግ ውስጥ ምንም ምርቶች የሉም።",
    units: "ክፍሎች",
    fillRequiredFields: "እባክዎ ሁሉንም አስፈላጊ ቦታዎች ይሙሉ።",
    failedSaveProduct: "ምርቱን ማስቀመጥ አልተሳካም።",
    confirmDeleteProduct: "ይህን ምርት ይሰርዙ?",
    failedDeleteProduct: "ምርቱን መሰረዝ አልተሳካም።",
    phProductName: "ለምሳሌ፦ AcousticMax Wireless Pro",
    phBrand: "ለምሳሌ፦ AlphaSonic Labs",
  },
  fr: {
    dir: "ltr",
    lang: "fr",
    brandNamePart1: "MERKATO",
    brandNamePart2: "BOUTIQUE",
    subtitle: "Marché Panafricain & Moyen-Orient",
    searchPlaceholder: "Rechercher parmi plus de 5 000 produits...",
    btnCart: "Ajouter au Panier",
    basketTitle: "Résumé du Panier",
    basketEmpty: "Le panier est vide.",
    totalEst: "Total Estimé",
    checkoutBtn: "Passer à la Caisse",

    allProducts: "TOUS LES PRODUITS",
    electronics: "ÉLECTRONIQUE",
    fashion: "MODE & VÊTEMENTS",
    groceries: "ÉPICERIE",
    beauty: "PRODUITS DE BEAUTÉ",
    household: "ARTICLES MÉNAGERS",
    accessories: "ACCESSOIRES",

    deliverTo: "LIVRER À",
    dashboard: "Tableau de bord",
    adminBadge: "ADMIN",
    logout: "Déconnexion",
    signIn: "SE CONNECTER",
    signUp: "S'INSCRIRE",
    forgotPassword: "Mot de passe oublié?",

    footerCopy:
      "© 2026 Hub de marché Merkato Store. Toutes les routes sécurisées via les spécifications PCI-DSS Niveau 1.",
    footerSecurity: "Pipeline de Déploiement Sécurisé TLS 1.3",
  },
  es: {
    dir: "ltr",
    lang: "es",
    brandNamePart1: "MERKATO",
    brandNamePart2: "TIENDA",
    subtitle: "Mercado Panafricano y Medio Oriente",
    searchPlaceholder: "Buscar más de 5.000 productos...",
    btnCart: "Añadir al Carrito",
    basketTitle: "Resumen de la Cesta",
    basketEmpty: "El carrito está vacío.",
    totalEst: "Total Estimado",
    checkoutBtn: "Proceder al Pago",

    allProducts: "TODOS LOS PRODUCTOS",
    electronics: "ELECTRÓNICA",
    fashion: "ROPA Y MODA",
    groceries: "COMESTIBLES",
    beauty: "PRODUCTOS DE BELLEZA",
    household: "ARTÍCULOS DEL HOGAR",
    accessories: "ACCESORIOS",

    deliverTo: "ENVIAR A",
    dashboard: "Panel de control",
    adminBadge: "ADMIN",
    logout: "Cerrar sesión",
    signIn: "INICIAR SESIÓN",
    signUp: "REGISTRARSE",
    forgotPassword: "¿Olvidaste tu contraseña?",

    footerCopy:
      "© 2026 Centro de mercado Merkato Store. Rutas seguras mediante especificaciones PCI-DSS Nivel 1.",
    footerSecurity: "Canal de Implementación Seguro TLS 1.3",
  },
  pt: {
    dir: "ltr",
    lang: "pt",
    brandNamePart1: "MERKATO",
    brandNamePart2: "LOJA",
    subtitle: "Mercado Panafricano e Médio Oriente",
    searchPlaceholder: "Buscar mais de 5.000 produtos...",
    btnCart: "Adicionar ao Carrinho",
    basketTitle: "Resumo do Carrinho",
    basketEmpty: "O carrinho está vazio.",
    totalEst: "Total Estimé",
    checkoutBtn: "Prosseguir para o Pagamento",

    allProducts: "TODOS OS PRODUTOS",
    electronics: "ELETRÔNICOS",
    fashion: "MODA & VESTUÁRIO",
    groceries: "MERCEARIA",
    beauty: "PRODUITS DE BEAUTÉ",
    household: "UTENSÍLIOS DOMÉSTICOS",
    accessories: "ACESSÓRIOS",

    deliverTo: "ENVIAR PARA",
    dashboard: "Painel",
    adminBadge: "ADMIN",
    logout: "Sair",
    signIn: "ENTRAR",
    signUp: "CADASTRAR-SE",
    forgotPassword: "Esqueceu a senha?",

    footerCopy:
      "© 2026 Hub de mercado Merkato Store. Rotas seguras por meio das especificações PCI-DSS Nível 1.",
    footerSecurity: "Pipeline de Implantação Seguro TLS 1.3",
  },
  sw: {
    dir: "ltr",
    lang: "sw",
    brandNamePart1: "MERKATO",
    brandNamePart2: "DUKA",
    subtitle: "Soko la Pan-African & Mashariki ya Kati",
    searchPlaceholder: "Tafuta bidhaa 5,000+ za kikanda...",
    btnCart: "Weka Kwenye Kikapu",
    basketTitle: "Muhtasari wa Kikapu",
    basketEmpty: "Kikapu kiko tupu.",
    totalEst: "Jumla Inayokadiriwa",
    checkoutBtn: "Endelea Kwenye Malipo",

    allProducts: "BIDHAA ZOTE",
    electronics: "ELEKTRONIKI",
    fashion: "MAVAZI NA MITINDO",
    groceries: "BIDHAA ZA CHAKULA",
    beauty: "BIDHAA ZA UREMBO",
    household: "VIFAA VYA NYUMBANI",
    accessories: "VIFAA VYA ZIADA",

    deliverTo: "WELEKEZA KWA",
    dashboard: "Dashboard",
    adminBadge: "ADMIN",
    logout: "Ondoka",
    signIn: "INGIA",
    signUp: "JISAJILI",
    forgotPassword: "Umesahau Nywila?",

    footerCopy:
      "© 2026 Kitovu cha Soko la Merkato Store. Njia zote zimeidhinishwa kupitia maelezo ya PCI-DSS Ngazi ya 1.",
    footerSecurity: "TLS 1.3 Njia Salama ya Upelekaji",
  },
};

export function LanguageProvider({ children }) {
  const [locale, setLocale] = useState("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const cachedLocale = localStorage.getItem("MERKATO_LOCALE");
    if (cachedLocale && DICTIONARY[cachedLocale]) setLocale(cachedLocale);
    setMounted(true);
  }, []);

  const switchLanguage = (langCode) => {
    if (DICTIONARY[langCode]) {
      setLocale(langCode);
      if (typeof window !== "undefined") {
        localStorage.setItem("MERKATO_LOCALE", langCode);
      }
    }
  };

  return (
    <LanguageContext.Provider
      value={{ locale, t: DICTIONARY[locale] || DICTIONARY.en, switchLanguage }}
    >
      <div
        dir={mounted ? (DICTIONARY[locale]?.dir || "ltr") : "ltr"}
        suppressHydrationWarning={true}
      >
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export const useTranslationEngine = () => useContext(LanguageContext);
